```{r}
library(fs)
library(raster)
library(terra)
library(tidyverse)
library(sf)
library(sp)
library(ggplot2)
library(here)
library(janitor)
library(countrycode)
library(tmap)
library(tmaptools)
```

```{r}
countries<-sf::st_read(here("data","World_Countries_Generalized","World_Countries_Generalized.shp"))
mycsv <- read_csv(here::here("data","gii-index.csv") ) 
```

```{r}
mycsv <- mycsv %>%
  mutate(difference = gii_2019 - gii_2010)
diff<-mycsv%>%
  select(country,difference)
```

```{r}
countries<- countries%>%
  clean_names()%>%
  left_join(diff,difference,
            by = c("country" = "country"))
```

```{r}
tmap_mode("plot")
qtm(countries, 
    fill = "difference")
```

```{r}

tmap_object <- tm_shape(countries) +
  tm_borders(lwd = 0.3) +
  tm_text(text = "countryaff", col="lightblue4", size = 0.2) +
  tm_fill(col = "difference", palette = "Blues", n = 7,contrast = c(0.8, 1)) +
  tm_compass(position = c("left", "bottom"), type = "arrow", text.size = 0.3) + 
  tm_scale_bar(position = c("left", "bottom"), text.size = 0.3) +
  tm_layout(title = "Difference in global gender inequality data between 2010 and 2019",title.size = 0.7,legend.position = c("right", "bottom"), legend.text.size = 0.3,legend.title.size = 0.5)


tmap_object

```

